### ISSUE TITLE
Bug in Open for variables that are derivatives

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Decapodes.jl#134]
It looks like if you want to expose a variable that is a derivative, you can't.

MWE:

```julia
using Test
using Decapodes
using Catlab

dexpr = Decapodes.parse_decapode(quote
  X::Form0{Point}
  V::Form0{Point}

  k::Constant{Point}

  ∂ₜ(X) == V
  ∂ₜ(V) == -1*k*(X)
end
)

A = dom(legs(Open(SummationDecapode(dexpr), [:V]))[1])
@test nparts(A, :Var) == 1
```

**Comment by lukem12345** [comment]
This is because we do a renaming by appending dots. e.g. Here, V becomes X \dot \dot.

```julia-repl
julia> SummationDecapode(dexpr)
SummationDecapode{Any, Any, Symbol} with elements Var = 1:6, TVar 
= 1:2, Op1 = 1:2, Op2 = 1:2, Σ = 1:0, Summand = 1:0, Type = 1:0, Operator = 1:0, Name = 1:0
┌─────┬──────────┬────────┐ 
│ Var │     type │   name │ 
├─────┼──────────┼────────┤ 
│   1 │    Form0 │      X │ 
│   2 │    Form0 │      Ẋ │ 
│   3 │ Constant │      k │ 
│   4 │    infer │ mult_1 │ 
│   5 │    infer │      Ẋ̇ │
│   6 │  Literal │     -1 │ 
└─────┴──────────┴────────┘ 
┌──────┬──────┐
│ TVar │ incl │
├──────┼──────┤
│    1 │    2 │
│    2 │    5 │
└──────┴──────┘
┌─────┬─────┬─────┬─────┐
│ Op1 │ src │ tgt │ op1 │
├─────┼─────┼─────┼─────┤
│   1 │   1 │   2 │  ∂ₜ │
│   2 │   2 │   5 │  ∂ₜ │
└─────┴─────┴─────┴─────┘
┌─────┬───────┬───────┬─────┬─────┐
│ Op2 │ proj1 │ proj2 │ res │ op2 │
├─────┼───────┼───────┼─────┼─────┤
│   1 │     6 │     3 │   4 │   * │
│   2 │     4 │     1 │   5 │   * │
└─────┴───────┴───────┴─────┴─────┘
```

**Comment by lukem12345** [comment]
@jpfairbanks 

The renaming-with-dot behavior should get changed, but just to ascertain whether composition of derivatives works, does using X dot dot instead of V in your MWE work with whatever composition you were attempting?

**Comment by jpfairbanks** [comment]
Yes, that workaround works. I guess this is a general problem about special casing the decapodes implementation to the DEC. Maybe we should refactor out the diagrammatic equations part and then have the parts that assume special structure of DEC as postprocessing.

**Comment by lukem12345** [comment]
I think the real reason here is that sometimes users write `\partial\_t(foo) = d(bar)`. But they never provide a human-readable name for what to call this quantity, so we rename it to foo dot. This renaming is too aggressive, but not directly related to anything DEC. But yes such a refactoring should be considered.

**Comment by lukem12345** [comment]
Calling this quantity X dot dot gives the human some information that this is a double derivative without having to do any analysis of the TVar table. Calling it V respects the way that the user specified variable names in the macro. Both naming conventions are nice in their own way. The latter should probably be preferred since the former loses information. In the PR that closes this, I want to provide a function that does the dot renaming in its current aggressive form, but do the respectful non-renaming by default. Best of both worlds.
