### ISSUE TITLE
Refactor into modules?

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Decapodes.jl#139]
We have 4 big features of Decapodes

1. The language for specifying the Diagrammatic Equations. This depends on MLStyle but doesn't depend on Catlab
2. The interpreter that builds an ACSet for the diagrammatic equations. This depends on Catlab and Combinatorial Spaces
3. The code that generates a timestep of the solver from the Combinatorial Operators and the Mesh. this doesn't depend on the ODE solvers or SciML ecosystem
4. The solvers. This is where we need to actually depend on SciML
5. Plotting, can be finicky between different systems in terms of the plotting backends. 

We could consider using the new optional dependency mechanism in julia 1.9 to make the decapodes package less heavyweight of an installation.

We could also consider factoring out DiagrammaticEquations into its own package that doesn't provide any operators, just the language for specifying the equations and the ACSets for representing them.

**Comment by jpfairbanks** [comment]
This issue brought to you by 

Precompiling project...
  Progress [=======================================> ]  220/226
  ◐ OrdinaryDiffEq
  ◐ GLMakie

**Comment by lukem12345** [comment]
This sounds all well and good to me.

To back-diagnose what led to this current state of affairs:
- Decapodes needed to before be an "everything app" for scientific computing. Because...
- Our target audience for some time was people who are neither native Julians nor programmers. Rather they were scientists who just want <10 click guide to start specifying and running sims. That is to say, the "core functionality" became blurred
- That is, not only was Decapodes.jl a core library for these diagrams of equations, by installing VSCode and adding Decapodes was meant to give you a scientific computing environment/ GUI & TUI ! (Which it currently does). This has led to some confusion with our industry partners as to what is "in scope". A **general** library for **making GIFs** of scientific simulations is likely too broad. As is recreating Blender scripts, although one could interpret CombinatorialSpaces code in that way. That isn't to say we shouldn't make it easy to extract data out of the system.
- Specifying optional dependencies for tests and submodules has changed a lot in Julia just over the past year.

**Comment by jpfairbanks** [comment]
@olynch has brought up an issue in SyntacticModels that makes this even more pressing. We should get this done sooner rather than later.

**Comment by jpfairbanks** [comment]
@quffaro and @KevinArlin, can you work together to pull the diagrammatic equations part out of Decapodes.jl and into a new package DiagrammaticEquations.jl following the AlgebraicTemplate.jl?

**Comment by jpfairbanks** [comment]
Closed by DiagrammaticEquations.jl
