### ISSUE TITLE
Download meshes as individual artifacts

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/Decapodes.jl#65]
> Should each mesh be its own artifact? I just brought this up to date with master locally and the tests pass. So we could merge now and then decide if we want individual artifacts later. In case that improves performance. Like you only download artifacts as you load them. 

__Originally posted by @jpfairbanks in https://github.com/AlgebraicJulia/Decapodes.jl/pull/59#issuecomment-1272165586__

Currently, for a user to call `loadmesh(ThermoIcosphere())`, all meshes are downloaded in one tarball and unpacked. This is convenient for users who plan on running simulations on a UVsphere discretization and an icosphere discretization of the thermosphere, but not for users who already know which mesh they want to use.

We want to avoid the case in which there are 2 copies of each mesh downloaded (i.e. via its own tarball and via the tarball of all meshes). `Artifacts` may have tooling to help in this case.

Tagging these artifacts as `lazy = true`, may also be a good idea, so they are not downloaded when a user adds `Decapodes` as a dependency.

Also of note: when the `tests` are run, all meshes are downloaded, since the `meshes.jl` tests check that each mesh is of proper dimensions.

So, it is also worth deciding whether we should remove the `meshes.jl` tests from the `runtests.jl` script and instead run them as an optional testset somehow.

**Comment by jpfairbanks** [comment]
I think it is fine for the tests to download all the meshes. That way we know there is a way to force the downloading of all the meshes. I would appreciate that because I often git pull right before going on a trip and it would be convenient for Pkg.test to make sure all the artifacts were downloaded. 

But then we still have the opportunity to let people download meshes as they need them. Which will be important as the number and variety of meshes increases. Particularly when we start doing stability studies we will make a bunch of meshes of the same object at different resolutions.

**Comment by lukem12345** [comment]
I will check on a system with an empty `.julia/artifacts` directory that meshes are not downloaded when `using Decapodes` is called, and then run `]test` to check that the appropriate directory is populated, and report back. This sounds like the behavior that you want.
